// Generated by CoffeeScript 1.6.1
var SDK, sdk;

SDK = (function() {

  function SDK() {}

  SDK.prototype.construtor = function() {
    var _this = this;
    return window.onhashchange = function(event) {
      return _this.onMessage(event.newURL);
    };
  };

  SDK.prototype.onMessage = function(msg) {
    var args, fn, id, part1, part2, _ref, _ref1;
    _ref = JSON.parse(msg), id = _ref.id, fn = _ref.fn, args = _ref.args;
    _ref1 = fn.split('.'), part1 = _ref1[0], part2 = _ref1[1];
    fn = this[part1][part2];
    return fn.call(this, {
      id: id,
      args: args
    });
  };

  SDK.prototype.user = {
    stuid: function() {
      return "3000000000";
    },
    pwd: function() {
      return "123456";
    }
  };

  SDK.prototype.kvdb = {
    get: function(args) {
      var id, key, msg, _ref;
      _ref = args, id = _ref.id, args = _ref.args;
      key = args.key;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.getItem(key);
      } catch (e) {
        msg.error = e;
      }
      return M.onMessage(msg);
    },
    set: function(args) {
      var id, key, msg, value, _ref;
      _ref = args, id = _ref.id, args = _ref.args;
      key = args.key, value = args.value;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.setItem(key, value);
      } catch (e) {
        msg.error = e;
      }
      return M.onMessage(msg);
    },
    remove: function(args) {
      var id, key, msg, _ref;
      _ref = args, id = _ref.id, args = _ref.args;
      key = args.key;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.removeItem(key);
      } catch (e) {
        msg.error = e;
      }
      return M.onMessage(msg);
    },
    clear: function(args) {
      var id, msg;
      id = args.id;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.clear();
      } catch (e) {
        msg.error = e;
      }
      return M.onMessage(msg);
    }
  };

  return SDK;

})();

sdk = new SDK;
