// Generated by CoffeeScript 1.6.1
var SDK;

SDK = (function() {

  function SDK() {
    var id;
    $(window).on('hashchange', function() {
      return window.location.reload();
    });
    id = window.location.hash.replace(new RegExp('#', 'g'), '');
    if (id.length < 1) {
      window.location.hash = 'qiuShiGou';
    } else {
      this.loadPlugin(id);
    }
  }

  SDK.prototype.onPluginLoad = function(e) {
    var style;
    style = $('<link>')[0].cloneNode(true);
    style.href = "../../sdk/css/scrollbar.css";
    style.rel = 'stylesheet';
    style.type = 'text/css';
    style.onload = function() {
      var widthWithoutScrollbar;
      widthWithoutScrollbar = $('object').contents().find('html').width();
      $('#wrap').css({
        width: widthWithoutScrollbar + 'px',
        'padding-left': 300 - widthWithoutScrollbar + 'px'
      });
      return $('#wrap').animate({
        opacity: 1
      });
    };
    return $('object').contents().find('head').append(style);
  };

  SDK.prototype.loadPlugin = function(pluginID) {
    var object, src,
      _this = this;
    src = "../plugins/" + pluginID + "/index.html";
    object = $('<object></object>')[0].cloneNode(true);
    object.height = 450;
    object.width = 300;
    object.data = src;
    object.onload = function(e) {
      return _this.onPluginLoad(e);
    };
    return $('#wrap').html(object);
  };

  SDK.prototype.onMessage = function(url) {
    var args, fn, id, part1, part2, prefix, _ref, _ref1;
    prefix = 'data:text/qscmobile-msg;base64,';
    if (url.indexOf(prefix) > -1) {
      url = url.replace('data:text\/qscmobile-msg;base64', '');
      this.onMessage(url);
    }
    _ref = JSON.parse(msg), id = _ref.id, fn = _ref.fn, args = _ref.args;
    _ref1 = fn.split('.'), part1 = _ref1[0], part2 = _ref1[1];
    fn = this[part1][part2];
    return fn.call(this, {
      id: id,
      args: args
    });
  };

  SDK.prototype.sendMessage = function(msg) {};

  SDK.prototype.user = {
    stuid: function() {
      return "3000000000";
    },
    pwd: function() {
      return "123456";
    }
  };

  SDK.prototype.kvdb = {
    get: function(args) {
      var id, key, msg, _ref;
      _ref = args, id = _ref.id, args = _ref.args;
      key = args.key;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.getItem(key);
      } catch (e) {
        msg.error = e;
      }
      return this.sendMessage(msg);
    },
    set: function(args) {
      var id, key, msg, value, _ref;
      _ref = args, id = _ref.id, args = _ref.args;
      key = args.key, value = args.value;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.setItem(key, value);
      } catch (e) {
        msg.error = e;
      }
      return this.sendMessage(msg);
    },
    remove: function(args) {
      var id, key, msg, _ref;
      _ref = args, id = _ref.id, args = _ref.args;
      key = args.key;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.removeItem(key);
      } catch (e) {
        msg.error = e;
      }
      return this.sendMessage(msg);
    },
    clear: function(args) {
      var id, msg;
      id = args.id;
      msg = {
        id: id
      };
      try {
        msg.data = localStorage.clear();
      } catch (e) {
        msg.error = e;
      }
      return this.sendMessage(msg);
    }
  };

  return SDK;

})();

$(function() {
  return $(document).ready(function() {
    window.sdk = new SDK;
    return console.log(sdk);
  });
});
